/**
 * Articles du blog, écrits en Markdown dans content/articles/<slug>.md (voir le README de ce
 * dossier) et convertis au build par scripts/articles.mjs.
 */
import { generatedArticles } from './articles.generated';

export interface Article {
    /** URL de l'article : /articles/<slug>, d'après le nom du fichier */
    slug: string;
    /** Titre affiché (h1) */
    title: string;
    /** Balise <title>, « – BeGooDev » compris : 20 à 65 caractères */
    metaTitle: string;
    /** Meta description et résumé dans la liste : 70 à 160 caractères */
    description: string;
    category: string;
    /** Date de publication, AAAA-MM-JJ */
    date: string;
    /** Contenu converti du Markdown en HTML */
    html: string;
    /**
     * Brouillon : la page est générée et consultable par son lien, mais en noindex,
     * absente de « À lire aussi », du sitemap et de la liste du blog (sauf sous ng serve).
     */
    draft?: boolean;
}

/** Tous les articles, brouillons compris, du plus récent au plus ancien. */
export const allArticles: Article[] = generatedArticles;

/** Articles publiés, du plus récent au plus ancien. */
export const articles = allArticles.filter((article) => !article.draft);

export const drafts = allArticles.filter((article) => article.draft);

export const findArticle = (slug: string) => allArticles.find((article) => article.slug === slug);

/** Temps de lecture estimé, à 200 mots par minute. */
export const readingTime = (article: Article) => {
    const words = article.html.replace(/<[^>]+>/g, ' ').split(/\s+/).filter(Boolean).length;
    return Math.max(1, Math.round(words / 200));
};

/** « 7 octobre 2026 » ; independent of the app locale, which stays the default en-US. */
export const formatDate = (date: string) =>
    new Date(`${date}T00:00:00Z`).toLocaleDateString('fr-FR', { day: 'numeric', month: 'long', year: 'numeric', timeZone: 'UTC' });

/** Share images, in the 16:9, 4:3 and 1:1 ratios Google recommends; generated by pnpm images:articles. */
export const articleImageSizes = [
    { ratio: '16x9', width: 1200, height: 675 },
    { ratio: '4x3', width: 1200, height: 900 },
    { ratio: '1x1', width: 1200, height: 1200 },
];

/** Path of an article's share image, e.g. /img/articles/<slug>-16x9.png */
export const articleImage = (article: Article, ratio = '16x9') => `/img/articles/${article.slug}-${ratio}.png`;
